### ISSUE TITLE
Webpack trows error when trying to load this library

### ISSUE THREAD

**Issue by GTP95** [jshttp/mime-types#98]
Greetings,

I'm trying to use this library inside a browser extension's ContentScript, but as soon as I try to import it (even without calling any function from this library) I get the following error inside Chromium's console:
```
ncaught Error: Cannot find module 'path'
    at webpackMissingModule (index.js:16:1)
    at ./node_modules/mime-types/index.js (index.js:16:1)
    at __webpack_require__ (bootstrap:19:1)
    at gmailInteraction.js:13:1
    at gmailInteraction.js:124:1
    at gmailInteraction.js:124:1
webpackMissingModule @ index.js:16
./node_modules/mime-types/index.js @ index.js:16
__webpack_require__ @ bootstrap:19
(anonymous) @ gmailInteraction.js:13
(anonymous) @ gmailInteraction.js:124
(anonymous) @ gmailInteraction.js:124
```
To import this library, I tried both `const mime=require("mime-types")` and `import * as mime from "mime-types"` but both give the same error, only the call stack looks sligtly different. For reference, the former error message was the one with the `require`method, while the following is the one I get with the `import` method:
```
Uncaught Error: Cannot find module 'path'
    at webpackMissingModule (index.js:16:1)
    at ./node_modules/mime-types/index.js (index.js:16:1)
    at __webpack_require__ (bootstrap:19:1)
    at nonce:1:1
    at gmailInteraction.js:124:1
    at gmailInteraction.js:124:1
    ```
    What am I missing?

**Comment by dougwilson** [comment]
Hi @GTP95 sorry for your issue. As noted in the readme, this module is for Node.js. There is an open issue regarding web browser support, though I don't use any modules in the web browser and no one has contributed said support so far. Until support for other environments besides Node.js is added, you are likely on your own.

**Comment by antoyne7** [comment]
Hi, your issue might be related to Webpack removing some polyfills for node core modules
you can try this: https://stackoverflow.com/a/65542520
